### ISSUE TITLE
Penilaian Tugas MKKD

### ISSUE THREAD

**Issue by fajarwz** [arifaji18/anssoscerdig#1]
halo mas arif, saya fajar, salah satu mentor kecerdasan digital (MKKD). saya mau memeriksa tugas kelompok mas. mohon submit github pages asli dari repo ini, ini bukan github pages yg dimaksud dalam tugas. contoh link dan penampakan github pages yg dimaksud itu seperti ini https://ryhn7.github.io/Rousillion_Responsive-Web-Restaurant/ . silakan submit ulang ya kalau bisa, terima kasih

**Comment by arifaji18** [comment]
Selamat malam, mas Fajar.
Mohon maaf saya mengganggu waktunya.
Berkaitan dengan tugas MKKD seperti yang dimaksud, saya kurang paham dengan
intruksi bagaimana cara submit githubnya. Kalau boleh tau, bagaimana tata
caranya ya, mas?
Terima kasih sebelumnya. Selamat malam

**Comment by fajarwz** [comment]
seperti ini mas https://progate.com/docs/github-pages

**Comment by arifaji18** [comment]
Terima kasih banyak, mas. Sedang kami usahakan🙏

**Comment by arifaji18** [comment]
Mohon maaf, mas. Kami sudah mengupayakan semampu kami tetapi ada beberapa
code yang muncul tidak sesuai apa yang kita buat di Visual Studio Code.
berikut adalah link githhubnya https://arifaji18.github.io/anssoscerdig/
 🙏🙏

**Comment by fajarwz** [comment]
itu tag penutupnya banyak yg belum bener

**Comment by arifaji18** [comment]
berikut tugas proyek yang sudah kami perbaiki lagi, mohon maaf jika masih
banyak kekurangan dan keterbatasan.
https://arifaji18.github.io/a120.github.io/

**Comment by fajarwz** [comment]
okee
